# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 250, 341, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 321, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name_editline = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_editline.setObjectName("name_editline")
        self.gridLayout.addWidget(self.name_editline, 0, 1, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.location_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.location_label.setFont(font)
        self.location_label.setObjectName("location_label")
        self.gridLayout.addWidget(self.location_label, 1, 0, 1, 1)
        self.location_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.location_combobox.setObjectName("location_combobox")
        self.location_combobox.addItem("")
        self.location_combobox.addItem("")
        self.gridLayout.addWidget(self.location_combobox, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create database"))
        self.name_label.setText(_translate("Dialog", "Name of database:"))
        self.location_label.setText(_translate("Dialog", "Where database should be created ?"))
        self.location_combobox.setItemText(0, _translate("Dialog", "Localy"))
        self.location_combobox.setItemText(1, _translate("Dialog", "Remotly"))
