# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_column_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.table_is_null = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.table_is_null.setObjectName("table_is_null")
        self.table_is_null.addItem("")
        self.table_is_null.addItem("")
        self.gridLayout.addWidget(self.table_is_null, 2, 1, 1, 1)
        self.table_attr = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.table_attr.setObjectName("table_attr")
        self.table_attr.addItem("")
        self.table_attr.addItem("")
        self.table_attr.addItem("")
        self.table_attr.addItem("")
        self.table_attr.addItem("")
        self.table_attr.addItem("")
        self.gridLayout.addWidget(self.table_attr, 1, 1, 1, 1)
        self.table_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.table_name.setObjectName("table_name")
        self.gridLayout.addWidget(self.table_name, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New column"))
        self.label.setText(_translate("Dialog", "Name"))
        self.label_3.setText(_translate("Dialog", "Is null"))
        self.label_2.setText(_translate("Dialog", "Attribute"))
        self.table_is_null.setItemText(0, _translate("Dialog", "True"))
        self.table_is_null.setItemText(1, _translate("Dialog", "False"))
        self.table_attr.setItemText(0, _translate("Dialog", "int"))
        self.table_attr.setItemText(1, _translate("Dialog", "float"))
        self.table_attr.setItemText(2, _translate("Dialog", "str"))
        self.table_attr.setItemText(3, _translate("Dialog", "bool"))
        self.table_attr.setItemText(4, _translate("Dialog", "color"))
        self.table_attr.setItemText(5, _translate("Dialog", "colorInvl"))
