# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_table_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_column(object):
    def setupUi(self, new_column):
        new_column.setObjectName("new_column")
        new_column.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_column)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(new_column)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.table_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.table_name.setObjectName("table_name")
        self.gridLayout.addWidget(self.table_name, 0, 1, 1, 1)

        self.retranslateUi(new_column)
        self.buttonBox.accepted.connect(new_column.accept)
        self.buttonBox.rejected.connect(new_column.reject)
        QtCore.QMetaObject.connectSlotsByName(new_column)

    def retranslateUi(self, new_column):
        _translate = QtCore.QCoreApplication.translate
        new_column.setWindowTitle(_translate("new_column", "New Column"))
        self.label.setText(_translate("new_column", "Name"))
